name: Update Latest Version

on:
  workflow_run:
    workflows: ["Deploy Pages"]
    types:
      - completed
    branches:
      - master

concurrency:
  group: "update-latest"
  cancel-in-progress: false

jobs:
  update-latest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Latest Version
        run: |
          # 버전 디렉토리 찾기
          cd files
          latest_version=$(ls -d v* | sort -V | tail -n 1)
          
          # latest 디렉토리 생성 또는 정리
          rm -rf latest
          mkdir -p latest
          
          # distribution.json 파일만 복사
          cp "$latest_version/distribution.json" latest/
          echo "Updated latest to version: $latest_version"

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add files/latest/distribution.json
          git commit -m "Update latest distribution.json" || exit 0
          git push
