name: Update Latest Version

on:
  workflow_run:
    workflows: ["Deploy Pages"]
    types:
      - completed
    branches:
      - master

concurrency:
  group: "update-latest"
  cancel-in-progress: false

jobs:
  update-latest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Latest Version
        run: |
          # 버전 디렉토리 찾기
          cd files
          latest_version=$(ls -d v* | sort -V | tail -n 1)
          
          # latest 디렉토리 생성 또는 정리
          rm -rf latest
          
          # 전체 디렉토리 복사
          cp -r "$latest_version" latest
          
          # index.html 생성
          cd latest
          echo "<!DOCTYPE html>
          <html>
          <head>
              <title>Latest Files</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .file-list { list-style: none; padding: 0; }
                  .file-list li { margin: 10px 0; }
                  .file-list a { text-decoration: none; color: #0366d6; }
                  .file-list a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <h1>Latest Files</h1>
              <ul class='file-list'>" > index.html
          
          # 파일 목록 생성
          find . -type f ! -name 'index.html' | sort | while read -r file; do
              file=${file#./}
              echo "<li><a href='$file'>$file</a></li>" >> index.html
          done
          
          echo "</ul></body></html>" >> index.html
          echo "Updated latest to version: $latest_version"

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add files/latest
          git commit -m "Update latest files to match $latest_version" || exit 0
          git push
