[landing]
updateAvailableTooltip = "업데이트가 있습니다"
usernamePlaceholder = "사용자 이름"
usernameEditButton = "편집"
settingsTooltip = "설정"
mediaGitHubURL = "https://github.com/hellosunghyun"

[settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "자바"
navLauncher = "런처"
navAbout = "정보"
navUpdates = "업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 관리"
tabAccountHeaderDesc = "계정을 추가하거나 관리합니다"
microsoftAccount = "마이크로소프트 계정"
addMicrosoftAccount = "마이크로소프트 계정 추가"
mojangAccount = "모장 계정"
addMojangAccount = "모장 계정 추가"
minecraftTabHeaderText = "게임 설정"
minecraftTabHeaderDesc = "게임 실행 관련 설정을 변경합니다"
gameResolutionTitle = "게임 해상도"
launchFullscreenTitle = "전체화면으로 실행"
autoConnectTitle = "자동 접속"
launchDetachedTitle = "독립 실행"
launchDetachedDesc = "런처와 게임을 독립적으로 실행합니다"
tabModsHeaderText = "모드 관리"
tabModsHeaderDesc = "모드를 관리하고 설정합니다"
switchServerButton = "서버 변경"
requiredMods = "필수 모드"
optionalMods = "선택 모드"
dropinMods = "추가 모드"
addMods = "모드 추가"
dropinRefreshNote = "(새로고침 필요)"
shaderpacks = "쉐이더팩"
shaderpackDesc = "쉐이더팩을 선택하여 게임의 그래픽을 향상시킬 수 있습니다"
selectShaderpack = "쉐이더팩 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "자바 실행 환경을 설정합니다"
memoryTitle = "메모리 설정"
maxRAM = "최대 메모리"
minRAM = "최소 메모리"
memoryDesc = "게임에 할당할 메모리를 설정합니다"
memoryTotalTitle = "전체 메모리"
memoryAvailableTitle = "사용 가능한 메모리"
javaExecutableTitle = "자바 실행 파일"
javaExecSelDialogTitle = "자바 실행 파일 선택"
javaExecSelButtonText = "찾아보기"
javaExecDesc = "자바 실행 파일을 선택하세요"
javaPathDesc = "자바 실행 파일 경로: {pathSuffix}"
jvmOptsTitle = "JVM 옵션"
jvmOptsDesc = "고급 사용자를 위한 JVM 실행 옵션입니다"
launcherTabHeaderText = "런처 설정"
launcherTabHeaderDesc = "런처 관련 설정을 변경합니다"
allowPrereleaseTitle = "시험판 업데이트"
allowPrereleaseDesc = "시험판 업데이트를 받습니다"

[ejs.landing]
updateAvailableTooltip = "업데이트가 있습니다"
usernamePlaceholder = "사용자 이름"
usernameEditButton = "편집"
settingsTooltip = "설정"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "모장 상태"
mojangStatusTooltipTitle = "서비스"
mojangStatusNETitle = "비필수"
newsButton = "소식"
launchButton = "시작"
launchButtonPlaceholder = "&#8226; 서버가 선택되지 않음"
launchDetails = "잠시만 기다려주세요.."
newsNavigationStatus = "{currentPage} / {totalPages}"
newsErrorLoadSpan = "소식을 확인하는 중.."
newsErrorFailedSpan = "소식을 불러오지 못했습니다"
newsErrorRetryButton = "다시 시도"
newsErrorNoneSpan = "소식 없음"

[ejs.login]
loginCancelText = "취소"
loginSubheader = "마인크래프트 로그인"
loginEmailError = "* 잘못된 값"
loginEmailPlaceholder = "이메일 또는 사용자 이름"
loginPasswordError = "* 필수 항목"
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "비밀번호를 잊으셨나요?"
loginRememberMeText = "로그인 유지"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "계정이 필요하신가요?"
loginPasswordDisclaimer1 = "비밀번호는 모장으로 직접 전송되며 저장되지 않습니다."
loginPasswordDisclaimer2 = "{appName}은 Mojang AB와 관련이 없습니다."

[ejs.loginOptions]
loginOptionsTitle = "로그인 옵션"
loginWithMicrosoft = "마이크로소프트로 로그인"
loginWithMojang = "모장으로 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "사용 가능한 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "계정 선택"
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "자바"
navLauncher = "런처"
navAbout = "정보"
navUpdates = "업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "계정을 추가하거나 관리합니다"
microsoftAccount = "마이크로소프트"
addMicrosoftAccount = "+ 마이크로소프트 계정 추가"
mojangAccount = "모장"
addMojangAccount = "+ 모장 계정 추가"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "게임 실행 관련 설정"
gameResolutionTitle = "게임 해상도"
launchFullscreenTitle = "전체화면으로 실행"
autoConnectTitle = "실행 시 자동으로 서버에 접속"
launchDetachedTitle = "게임을 런처와 별도로 실행"
launchDetachedDesc = "게임이 별도로 실행되지 않으면 런처를 닫을 때 게임도 함께 종료됩니다"
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "모드를 활성화하거나 비활성화합니다"
switchServerButton = "변경"
requiredMods = "필수 모드"
optionalMods = "선택 모드"
dropinMods = "추가 모드"
addMods = "모드 추가"
dropinRefreshNote = "(F5로 새로고침)"
shaderpacks = "쉐이더팩"
shaderpackDesc = "쉐이더를 활성화하거나 비활성화합니다. 쉐이더는 성능이 좋은 컴퓨터에서만 원활하게 작동합니다. 여기에 커스텀 팩을 추가할 수 있습니다."
selectShaderpack = "쉐이더팩 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "자바 설정을 관리합니다 (고급)"
memoryTitle = "메모리"
maxRAM = "최대 RAM"
minRAM = "최소 RAM"
memoryDesc = "권장 최소 RAM은 3기가바이트입니다. 최소값과 최대값을 같게 설정하면 렉이 줄어들 수 있습니다."
memoryTotalTitle = "전체"
memoryAvailableTitle = "사용 가능"
javaExecutableTitle = "자바 실행 파일"
javaExecSelDialogTitle = "자바 실행 파일 선택"
javaExecSelButtonText = "파일 선택"
javaExecDesc = "자바 실행 파일은 게임 실행 전에 검증됩니다"
javaPathDesc = "경로는 <strong>{pathSuffix}</strong>로 끝나야 합니다"
jvmOptsTitle = "추가 JVM 옵션"
jvmOptsDesc = "실행 시 JVM에 제공할 옵션입니다. <em>-Xms</em>와 <em>-Xmx</em>는 포함하지 마세요."
launcherTabHeaderText = "런처 설정"
launcherTabHeaderDesc = "런처 자체와 관련된 설정"
allowPrereleaseTitle = "시험판 업데이트 허용"
allowPrereleaseDesc = "시험판에는 완전히 테스트되거나 통합되지 않은 새로운 기능이 포함될 수 있습니다.<br>시험판 버전을 사용 중이라면 이 옵션은 항상 켜져있습니다."
dataDirectoryTitle = "데이터 디렉토리"
selectDataDirectory = "데이터 디렉토리 선택"
chooseFolder = "폴더 선택"
dataDirectoryDesc = "모든 게임 파일과 로컬 자바 설치가 데이터 디렉토리에 저장됩니다.<br>스크린샷과 월드 저장은 해당 서버 설정의 인스턴스 폴더에 저장됩니다."
aboutTabHeaderText = "정보"
aboutTabHeaderDesc = "현재 버전의 정보와 릴리스 노트를 확인합니다"
aboutTitle = "{appName}"
stableRelease = "정식 릴리스"
versionText = "버전 "
sourceGithub = "소스 코드 (GitHub)"
support = "지원"
devToolsConsole = "개발자 도구 콘솔"
releaseNotes = "릴리스 노트"
changelog = "변경 사항"
noReleaseNotes = "릴리스 노트 없음"
viewReleaseNotes = "GitHub에서 릴리스 노트 보기"
launcherUpdatesHeaderText = "런처 업데이트"
launcherUpdatesHeaderDesc = "런처의 업데이트를 다운로드, 설치하고 검토합니다"
checkForUpdates = "업데이트 확인"
whatsNew = "새로운 기능"
updateReleaseNotes = "업데이트 릴리스 노트"

[ejs.waiting]
waitingText = "마이크로소프트 대기 중.."

[ejs.welcome]
continueButton = "계속"

[js.discord]
waiting = "클라이언트 대기 중.."
state = "서버: {shortId}"

[js.index]
microsoftLoginTitle = "마이크로소프트 로그인"
microsoftLogoutTitle = "마이크로소프트 로그아웃"

[js.login]
login = "로그인"
loggingIn = "로그인 중"
success = "성공"
tryAgain = "다시 시도"

[js.login.error]
invalidValue = "* 잘못된 값"
requiredValue = "* 필수 항목"

[js.login.error.unknown]
title = "로그인 중 알 수 없는 오류"
desc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 확인하세요."

[js.landing.launch]
pleaseWait = "잠시만 기다려주세요.."
failureTitle = "실행 중 오류"
failureText = "자세한 내용은 콘솔(CTRL + Shift + i)을 확인하세요."
okay = "확인"

[js.landing.selectedAccount]
noAccountSelected = "선택된 계정 없음"

[js.landing.selectedServer]
noSelection = "선택된 서버 없음"
loading = "로딩 중.."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "시스템 정보 확인 중.."
noCompatibleJava = "호환되는 자바가<br>설치되어 있지 않습니다"
installJavaMessage = "마인크래프트를 실행하려면 64비트 자바 {major}가 필요합니다. 설치하시겠습니까?"
installJava = "자바 설치"
installJavaManually = "수동으로 설치"
javaDownloadPrepare = "자바 다운로드 준비 중.."
javaDownloadFailureTitle = "자바 다운로드 중 오류"
javaDownloadFailureText = "자세한 내용은 콘솔(CTRL + Shift + i)을 확인하세요."
javaRequired = "실행에 자바가<br>필요합니다"
javaRequiredMessage = '게임을 실행하려면 64비트 자바 {major}가 필요합니다.<br><br>자바를 수동으로 설치하는 방법은 <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">자바 관리 가이드</a>를 참고하세요.'
javaRequiredDismiss = "알겠습니다"
javaRequiredCancel = "뒤로"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK 배포판을 찾을 수 없습니다."
javaDownloadCorruptedError = "다운로드된 JDK의 해시가 잘못되었습니다. 파일이 손상되었을 수 있습니다."
extractingJava = "자바 압축 해제 중"
javaInstalled = "자바 설치 완료!"

[js.landing.dlAsync]
loadingServerInfo = "서버 정보 로딩 중.."
fatalError = "치명적 오류"
unableToLoadDistributionIndex = "배포 인덱스를 불러올 수 없습니다. 자세한 내용은 콘솔(CTRL + Shift + i)을 확인하세요."
pleaseWait = "잠시만 기다려주세요.."
errorDuringLaunchTitle = "실행 중 오류"
seeConsoleForDetails = "자세한 내용은 콘솔(CTRL + Shift + i)을 확인하세요."
validatingFileIntegrity = "파일 무결성 검증 중.."
errorDuringFileVerificationTitle = "파일 검증 중 오류"

[js.settings.account]
selectedAccount = "선택된 계정 "
logout = "로그아웃"

[js.settings.dropinMods]
removeButton = "제거"

[js.settings.java]
defaultJavaTitle = "번들된 자바 (권장)"

[js.settings.mods]
requiredMods = "필수 모드"
optionalMods = "선택적 모드"
selectedMods = "{selected} / {total} 모드 선택됨"
advancedOptions = "고급 옵션"
syncDesc = "서버와 모드 동기화 유지"
syncDescDisabled = "서버와 모드 동기화 비활성화됨"
notAvailable = "사용할 수 없음"

[js.settings.shader]
notAvailable = "사용할 수 없음"
selected = "선택됨"

[js.settings.updates]
checkForUpdates = "업데이트 확인"
checking = "확인 중.."
noUpdateAvailable = "업데이트 없음"
newUpdateAvailable = "새 업데이트 사용 가능!"
versionAvailable = "런처 {version}을(를) 사용할 수 있습니다."
download = "다운로드"
later = "나중에"

[js.uibinder]
confirmButton = "확인"
restartButton = "재시작"
ignoreButton = "무시"
confirmTitle = "확인"
restartTitle = "재시작 필요"
ignoreTitle = "경고"

[js.login.error.invalidCredentials]
title = "로그인 실패:<br>잘못된 자격 증명"
desc = "이메일 또는 비밀번호가 잘못되었습니다. 다시 시도하세요."

[js.login.error.rateLimit]
title = "로그인 실패:<br>너무 많은 시도"
desc = "너무 많은 로그인 시도가 있었습니다. 나중에 다시 시도하세요."

[js.login.error.noInternet]
title = "로그인 실패:<br>인터넷 연결 없음"
desc = "로그인하려면 인터넷 연결이 필요합니다."

[js.login.error.authDown]
title = "로그인 실패:<br>인증 서버 다운"
desc = "Mojang의 인증 서버가 현재 다운되었습니다. 나중에 다시 시도하세요."

[js.login.error.notPaid]
title = "로그인 실패:<br>게임 구매 필요"
desc = "이 계정으로 마인크래프트를 구매하지 않았습니다."

[js.login.error.invalidSession]
title = "로그인 실패:<br>잘못된 세션"
desc = "세션이 만료되었습니다. 다시 로그인하세요."

[js.login.error.invalidSalt]
title = "로그인 실패:<br>잘못된 솔트 버전"
desc = "잘못된 솔트 버전입니다."

[js.login.error.unsupportedMediaType]
title = "내부 오류:<br>지원되지 않는 미디어 타입"
desc = "지원되지 않는 미디어 타입입니다. 이 오류를 보고해주세요."

[js.login.error.accountGone]
title = "로그인 실패:<br>계정 마이그레이션"
desc = "계정이 마이크로소프트 계정으로 마이그레이션되었습니다. 마이크로소프트로 로그인하세요."
